app/app/urls.py
'''
    Copyright (C) 2018 Gitcoin Core

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU Affero General Public License as published
    by the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
    GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with this program. If not, see <http://www.gnu.org/licenses/>.

'''
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.contrib.sitemaps.views import sitemap
from django.urls import path, re_path
from django.views.i18n import JavaScriptCatalog

import avatar.views
import bounty_requests.views
import credits.views
import dashboard.embed
import dashboard.gas_views
import dashboard.helpers
import dashboard.tip_views
import dashboard.views
import dataviz.d3_views
import dataviz.views
import enssubdomain.views
# event:ethdenver2019
import event_ethdenver2019.views
import faucet.views
import gitcoinbot.views
import healthcheck.views
import kudos.views
import linkshortener.views
import marketing.views
import marketing.webhookviews
import retail.emails
import retail.views
import revenue.views
import tdi.views
from avatar.router import router as avatar_router
from dashboard.router import router as dbrouter
from grants.router import router as grant_router
from kudos.router import router as kdrouter

from .sitemaps import sitemaps

urlpatterns = [
    path('jsi18n/', JavaScriptCatalog.as_view(), name='javascript-catalog'),

    # create bounty
    url(r'^create?', dashboard.views.new_bounty, name='create_bounty'),  # TODO: Remove

    # inbox
    path('inbox/', include('inbox.urls', namespace='inbox')),

    # kudos
    path('kudos/', kudos.views.about, name='kudos_main'),
    path('kudos/about/', kudos.views.about, name='kudos_about'),
    path('kudos/marketplace/', kudos.views.marketplace, name='kudos_marketplace'),
    path('kudos/mint/', kudos.views.mint, name='kudos_mint'),
    path('kudos/send/', kudos.views.send_2, name='kudos_send'),
    path('kudos/send/3/', kudos.views.send_3, name='kudos_send_3'),
    path('kudos/send/4/', kudos.views.send_4, name='kudos_send_4'),
    re_path(r'^lazy_load_kudos/$', dashboard.views.lazy_load_kudos, name='lazy_load_kudos'),
    re_path(r'^kudos/receive/v3/(?P<key>.*)/(?P<txid>.*)/(?P<network>.*)?', kudos.views.receive, name='kudos_receive'),
    re_path(r'^kudos/redeem/(?P<secret>.*)/?$', kudos.views.receive_bulk, name='kudos_receive_bulk'),
    re_path(r'^kudos/search/$', kudos.views.search, name='kudos_search'),
    re_path(
        r'^kudos/(?P<address>\w*)/(?P<token_id>\d+)/(?P<name>\w*)',
        kudos.views.details_by_address_and_token_id,
        name='kudos_details_by_address_and_token_id'
    ),
    re_path(r'^kudos/(?P<kudos_id>\d+)/(?P<name>\w*)', kudos.views.details, name='kudos_details'),
    re_path(r'^kudos/address/(?P<handle>.*)', kudos.views.kudos_preferred_wallet, name='kudos_preferred_wallet'),
    re_path(r'^dynamic/kudos/(?P<kudos_id>\d+)/(?P<name>\w*)', kudos.views.image, name='kudos_dynamic_img'),

    # api views
    url(r'^api/v0.1/profile/(.*)?/keywords', dashboard.views.profile_keywords, name='profile_keywords'),
    url(
        r'^api/v0.1/profile/(.*)?/jobopportunity',
        dashboard.views.profile_job_opportunity,
        name='profile_job_opportunity'
    ),
    url(r'^api/v0.1/profile/(?P<handle>.*)', dashboard.views.profile_details, name='profile_details'),
    url(
        r'^api/v0.1/get_suggested_contributors',
        dashboard.views.get_suggested_contributors,
        name='get_suggested_contributors'
    ),
    url(
        r'^api/v0.1/social_contribution_email',
        dashboard.views.social_contribution_email,
        name='social_contribution_email'
    ),
    url(r'^api/v0.1/bountydocument', dashboard.views.bounty_upload_nda, name='bounty_upload_nda'),
    url(r'^api/v0.1/faucet/save/?', faucet.views.save_faucet, name='save_faucet'),
    url(r'^api/v0.1/', include(dbrouter.urls)),
    url(r'^api/v0.1/', include(kdrouter.urls)),
    url(r'^api/v0.1/', include(grant_router.urls)),
    url(r'^api/v0.1/', include(avatar_router.urls)),
    url(r'^actions/api/v0.1/', include(dbrouter.urls)),  # same as active
    url(r'^api/v0.1/users_search/', dashboard.views.get_users, name='users_search'),
    url(r'^api/v0.1/kudos_search/', dashboard.views.get_kudos, name='kudos_search'),
    # Health check endpoint
    re_path(r'^health/', include('health_check.urls')),
    re_path(r'^lbcheck/?', healthcheck.views.lbcheck, name='lbcheck'),
    re_path(r'^spec/?', healthcheck.views.spec, name='spec'),

    # grant views
    path('grants/', include('grants.urls', namespace='grants')),

    # dashboard views
    re_path(r'^onboard/(?P<flow>\w+)/$', dashboard.views.onboard, name='onboard'),
    re_path(r'^onboard/contributor/avatar/?$', dashboard.views.onboard_avatar, name='onboard_avatar'),
    url(r'^postcomment/', dashboard.views.post_comment, name='post_comment'),
    url(r'^dashboard/?', dashboard.views.dashboard, name='dashboard'),
    url(r'^explorer/?', dashboard.views.dashboard, name='explorer'),
    url(r'^hackathon/ethhack2019', dashboard.views.ethhack, name='ethhack_2019'),
    path('revenue/attestations/new', revenue.views.new_attestation, name='revenue_new_attestation'),

    # Hackathons / special events
    re_path(r'^hackathon/(?P<hackathon>.*)?/', dashboard.views.hackathon, name='hackathon'),
    re_path(r'^hackathon?/', dashboard.views.hackathon, name='hackathon_idx'),
    path('hackathon-list/', dashboard.views.get_hackathons, name='get_hackathons'),

    # action URLs
    url(r'^funder', retail.views.funder_bounties_redirect, name='funder_bounties_redirect'),
    re_path(
        r'^contributor/?(?P<tech_stack>.*)/?',
        retail.views.contributor_bounties_redirect,
        name='contributor_bounties_redirect'
    ),
    url(r'^bounties/funder', retail.views.funder_bounties, name='funder_bounties'),
    re_path(
        r'^bounties/contributor/?(?P<tech_stack>.*)/?', retail.views.contributor_bounties, name='contributor_bounties'
    ),
    re_path(r'^bounty/quickstart/?', dashboard.views.quickstart, name='quickstart'),
    url(r'^bounty/new/?', dashboard.views.new_bounty, name='new_bounty'),
    re_path(r'^bounty/change/(?P<bounty_id>.*)?', dashboard.views.change_bounty, name='change_bounty'),
    url(r'^funding/new/?', dashboard.views.new_bounty, name='new_funding'),  # TODO: Remove
    url(r'^new/?', dashboard.views.new_bounty, name='new_funding_short'),  # TODO: Remove
    # TODO: Rename below to bounty/
    path('issue/fulfill', dashboard.views.fulfill_bounty, name='fulfill_bounty'),
    path('issue/accept', dashboard.views.accept_bounty, name='process_funding'),
    path('issue/advanced_payout', dashboard.views.bulk_payout_bounty, name='bulk_payout_bounty'),
    path('issue/invoice', dashboard.views.invoice, name='invoice'),
    path('issue/payout', dashboard.views.payout_bounty, name='payout_bounty'),
    path('issue/increase', dashboard.views.increase_bounty, name='increase_bounty'),
    path('issue/cancel', dashboard.views.cancel_bounty, name='kill_bounty'),
    path('issue/refund_request', dashboard.views.refund_request, name='refund_request'),
    path('issue/cancel_reason', dashboard.views.cancel_reason, name='cancel_reason'),
    path('issue/contribute', dashboard.views.contribute, name='contribute'),
    path('issue/social_contribution', dashboard.views.social_contribution, name='social_contribution'),
    path('modal/social_contribution', dashboard.views.social_contribution_modal, name='social_contribution_modal'),
    path(
        '<str:bounty_network>/<int:stdbounties_id>/modal/funder_payout_reminder/',
        dashboard.views.funder_payout_reminder_modal,
        name='funder_payout_reminder_modal'
    ),

    # Rating
    path('modal/rating/<int:bounty_id>/<str:username>/', dashboard.views.rating_modal, name='rating_modal'),
    path('modal/rating_capture/', dashboard.views.rating_capture, name='rating_capture'),
    url(r'^api/v0.1/unrated_bounties/', dashboard.views.unrated_bounties, name='unrated_bounties'),

    # Notify Funder Modal Submission
    path(
        'actions/bounty/<str:bounty_network>/<int:stdbounties_id>/notify/funder_payout_reminder/',
        dashboard.views.funder_payout_reminder,
        name='funder_payout_reminder'
    ),
    path(
        'actions/bounty/<int:bounty_id>/extend_expiration/',
        dashboard.views.extend_expiration,
        name='extend_expiration'
    ),

    # Avatars
    path('avatar/', include('avatar.urls', namespace='avatar')),

    # Interests
    path('actions/bounty/<int:bounty_id>/interest/new/', dashboard.views.new_interest, name='express-interest'),
    path('actions/bounty/<int:bounty_id>/interest/remove/', dashboard.views.remove_interest, name='remove-interest'),
    path(
        'actions/bounty/<int:bounty_id>/interest/<int:profile_id>/uninterested/',
        dashboard.views.uninterested,
        name='uninterested'
    ),

    # View Bounty
    url(
        r'^issue/(?P<ghuser>.*)/(?P<ghrepo>.*)/(?P<ghissue>.*)/(?P<stdbounties_id>.*)',
        dashboard.views.bounty_details,
        name='issue_details_new3'
    ),
    url(
        r'^issue/(?P<ghuser>.*)/(?P<ghrepo>.*)/(?P<ghissue>.*)',
        dashboard.views.bounty_details,
        name='issue_details_new2'
    ),
    re_path(r'^funding/details/?', dashboard.views.bounty_details, name='funding_details'),

app/grants/urls.py
# -*- coding: utf-8 -*-
"""Handle grant URLs.

Copyright (C) 2018 Gitcoin Core

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published
by the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program. If not, see <http://www.gnu.org/licenses/>.

"""
from django.urls import path, re_path

from grants.views import (
    grant_details, grant_fund, grant_new, grant_new_v0, grants, leaderboard, milestones, new_matching_partner, profile,
    quickstart, subscription_cancel,
)

app_name = 'grants'
urlpatterns = [
    path('', grants, name='grants'),
    path('<int:grant_id>/<slug:grant_slug>', grant_details, name='details'),
    path('<int:grant_id>/<slug:grant_slug>/', grant_details, name='details2'),
    re_path(r'^new', grant_new, name='new'),
    re_path(r'^old', grant_new_v0, name='old'),
    path('<int:grant_id>/<slug:grant_slug>/milestones', milestones, name='milestones'),
    path('<int:grant_id>/<slug:grant_slug>/fund', grant_fund, name='fund'),
    path(
        '<int:grant_id>/<slug:grant_slug>/subscription/<int:subscription_id>/cancel',
        subscription_cancel,
        name='subscription_cancel'
    ),
    re_path(r'^profile', profile, name='profile'),
    re_path(r'^quickstart', quickstart, name='quickstart'),
    re_path(r'^leaderboard', leaderboard, name='leaderboard'),
    re_path(r'^matching-partners/new', new_matching_partner, name='new_matching_partner'),
]

app/dashboard/templates/shared/connect_metamask.html
{% comment %}
  Copyright (C) 2018 Gitcoin Core

  This program is free software: you can redistribute it and/or modify
  it under the terms of the GNU Affero General Public License as published
  by the Free Software Foundation, either version 3 of the License, or
  (at your option) any later version.

  This program is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
  GNU Affero General Public License for more details.

  You should have received a copy of the GNU Affero General Public License
  along with this program. If not, see <http://www.gnu.org/licenses/>.
{% endcomment %}
{% load i18n static %}
<div id="connect_metamask_error" class="metamask-error container-fluid" style="display: none;">
  <div class="row align-items-center px-4 py-5 text-center text-lg-left mx-lg-5">
    <div class="col-lg-6 offset-xl-1 col-xl-5 col-sm-12 py-5 px-5">
      <h3>{% trans "To continue," %} <br>
        {% trans "you'll need to connect Metamask." %}</h3>
      <p class="my-4">{% trans "Please connect MetaMask and refresh this page to continue." %}</p>
      <button class="btn btn-metamask btn-lg-padding" onclick="approve_metamask()">{% trans 'Connect Metamask' %}</button>
      <p class="mt-4 font-smaller-2">{% trans "Can't get web3 to work?" %}   <a href="https://github.com/gitcoinco/gitcoinco/issues/4" target="_blank" rel="noopener noreferrer">{% trans "Get help here." %}</a></p>
    </div>
    <div class="col-lg-6 col-xl-5 col-sm-12 text-center">
      <img src="{% static "v2/images/metamask/connect-metamask.svg" %}" alt="Metamask Logo" class="mw-100">
    </div>
  </div>
</div>

<style>
  #connect_metamask_error #metamask_connect {
    position: relative;
    bottom: 2px;
  }
</style>

app/dashboard/templates/shared/disqus.html
{% comment %}
  Copyright (C) 2018 Gitcoin Core

  This program is free software: you can redistribute it and/or modify
  it under the terms of the GNU Affero General Public License as published
  by the Free Software Foundation, either version 3 of the License, or
  (at your option) any later version.

  This program is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
  GNU Affero General Public License for more details.

  You should have received a copy of the GNU Affero General Public License
  along with this program. If not, see <http://www.gnu.org/licenses/>.
{% endcomment %}
<div id="disqus_thread"></div>
<script>

/**
*  RECOMMENDED CONFIGURATION VARIABLES: EDIT AND UNCOMMENT THE SECTION BELOW TO INSERT DYNAMIC VALUES FROM YOUR PLATFORM OR CMS.
*  LEARN WHY DEFINING THESE VARIABLES IS IMPORTANT: https://disqus.com/admin/universalcode/#configuration-variables*/
{% if page_url %}
  var disqus_config = function () {
  this.page.url = '{{page_url}}';  // Replace PAGE_URL with your page's canonical URL variable
  //this.page.identifier = PAGE_IDENTIFIER; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
  };
{% endif %}
(function() { // DON'T EDIT BELOW THIS LINE
var d = document, s = d.createElement('script');
s.src = 'https://gitcoin-1.disqus.com/embed.js';
s.setAttribute('data-timestamp', +new Date());
(d.head || d.body).appendChild(s);
})();
</script>
<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>

app/dashboard/templates/shared/gas_advisories.html
{% comment %}
  Copyright (C) 2018 Gitcoin Core

  This program is free software: you can redistribute it and/or modify
  it under the terms of the GNU Affero General Public License as published
  by the Free Software Foundation, either version 3 of the License, or
  (at your option) any later version.

  This program is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
  GNU Affero General Public License for more details.

  You should have received a copy of the GNU Affero General Public License
  along with this program. If not, see <http://www.gnu.org/licenses/>.
{% endcomment %}
{% load humanize %}
{% for ga in gas_advisories %}
<div class='gas_advisory red_warning'>
  <strong>
    {{ ga.created_on|naturaltime }}
  </strong> |
  <span>
    {{ ga.body|safe }}
  </span>
</div>
{% endfor %}

app/dashboard/templates/shared/gas_history.html
{% comment %}
  Copyright (C) 2018 Gitcoin Core

  This program is free software: you can redistribute it and/or modify
  it under the terms of the GNU Affero General Public License as published
  by the Free Software Foundation, either version 3 of the License, or
  (at your option) any later version.

  This program is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
  GNU Affero General Public License for more details.

  You should have received a copy of the GNU Affero General Public License
  along with this program. If not, see <http://www.gnu.org/licenses/>.
{% endcomment %}

<link rel="canonical" href="{% url 'gas_history_view' %}">

<style> /* set the CSS */

.axis {
  font-family: Arial, Helvetica, sans-serif;
  font-size: .8em;
}

.line {
  fill: none;
  stroke: steelblue;
  stroke-width: 2px;
}
{% for key, val in lines.items %}
.line.line_{{key}} {
  stroke: {{val}};
}
{% endfor %}
div.tooltip {
  position: absolute;
  max-width: 300px;
  padding: 3px 6px;
  color: grey;
  font-family: 'Droid Sans Mono', monospace;
  font-size: .7em;
  background: whitesmoke;
  border: 1px solid grey;
  border-radius: 3px;
  pointer-events: none;
  z-index: 9999;
}
@media screen and (min-width: 901px) {
  #key {
    right: 100px;
    float: right;
    top: 270px;
    position: absolute;
  }
}
@media screen and (max-width: 900px) {
  #key {
    position: initial;
  }
}
#key{
  text-align: right;
}
#key p{
  margin: 0px;
  font-size: 12px;
}

</style>

  <script src="https://d3js.org/d3.v4.min.js"></script>
  <script>

  var tooltip;

  tooltip = d3.select("body").append("div")
    .attr("class", "tooltip")
    .style("opacity", 0);

    var margin = {top: 20, right: 20, bottom: 50, left: 70},
        width = window.innerWidth - 200 - margin.left - margin.right,
        height = 500 - margin.top - margin.bottom;
  var initialWidth = width;
  var xScale = d3.scaleLinear().range([width, 0]);
  var yScale = d3.scaleLinear().range([height, 0]);

  // define the line
  var valueline = d3.line()
      .x(function(d) { return xScale(d.confirmation_time); })
      .y(function(d) { return yScale(d.gas_price); });

  var svg = d3.select("#graph")
      .attr("width", width)
      .attr("height", height + margin.top + margin.bottom)
    .append("g")
      .attr("transform", "translate(" + margin.left + "," + margin.top + ")");

  {% for key, gas_history in gas_histories.items %}
    var source = {{gas_history | safe}};
    data = []
    source.forEach(function(d) {
        d['confirmation_time'] = parseFloat(d[1])
        d['gas_price'] = parseFloat(d[0]);
        d.splice(0,2);
        data.push(d);
    });

    xScale.domain([0, d3.max(data, function(d) { return d.confirmation_time; })]).nice();
    yScale.domain([0, d3.max(data, function(d) { return {{max}}; })]).nice();

    svg.append("path")
      .data([data])
      .attr("class", "line line_{{key}}")
      .attr("d", valueline);

  {% endfor %}

  // x Axis
  svg.append("g")
      .attr("class", "x axis")
      .attr("transform", "translate(0," + height + ")")
      .call(d3.axisBottom(xScale));

  // text label for the x axis
  svg.append("text")
      .attr("transform",
            "translate(" + (width/2) + " ," +
                           (height + margin.top + 20) + ")")
      .style("text-anchor", "middle")
      .attr("class", "axis")
      .attr("class", "x-title")
      .text("{{breakdown_ui}}-ago");

  // y Axis
  svg.append("g")
    .call(d3.axisLeft(yScale));

  // text label for the y axis
  svg.append("text")
    .attr("transform", "rotate(-90)")
    .attr("y", 0 - margin.left)
    .attr("x",0 - (height / 2))
    .attr("dy", "2em")
    .attr("class", "axis")
    .style("text-anchor", "middle")
    .text("{{y_axis}}");

  function resize() {
    var newWidth = window.innerWidth - 100 - margin.left - margin.right;
    var height = 500 - margin.top - margin.bottom;
    if(newWidth < initialWidth) { // initialWidth determines max width of parent div in a way

      // Update the range of the scale with new width/height
      xScale.range([newWidth, 0]);
      yScale.range([height, 0]);

      svg.select(".x.axis") // resizes x axis
        .attr("transform", "translate(0," + height + ")")
        .call(d3.axisBottom(xScale));

      svg.select(".x-title") // resizes the positioning of the x axis title
        .attr("transform","translate(" + (newWidth/2) + " ," + (height + margin.top + 20) + ")")
        .style("text-anchor", "middle");

      svg.append("path") // updates line data to conform
        .data([data])
        .attr("class", "line line_{{key}}")
        .attr("d", valueline);
    }
  }
  // Call the resize function whenever a resize event occurs
  d3.select(window).on('resize', resize);

  </script>

app/dashboard/templates/shared/hours_worked.html
{% comment %}
  Copyright (C) 2018 Gitcoin Core

  This program is free software: you can redistribute it and/or modify
  it under the terms of the GNU Affero General Public License as published
  by the Free Software Foundation, either version 3 of the License, or
  (at your option) any later version.

  This program is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
  GNU Affero General Public License for more details.

  You should have received a copy of the GNU Affero General Public License
  along with this program. If not, see <http://www.gnu.org/licenses/>.
{% endcomment %}
{% load i18n %}
<div class="w-100 mt-2">
  <label class="form__label" for="hoursWorked">{% trans "Hours Worked" %}</label>
  <input name='hoursWorked' id='hoursWorked' class="form__input" type="number" placeholder="1 (feel free to approximate)" value="" min="0" step="0.1" />
</div>

app/dashboard/templates/shared/nav_auth.html
{% comment %}
  Copyright (C) 2018 Gitcoin Core

  This program is free software: you can redistribute it and/or modify
  it under the terms of the GNU Affero General Public License as published
  by the Free Software Foundation, either version 3 of the License, or
  (at your option) any later version.

  This program is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
  GNU Affero General Public License for more details.

  You should have received a copy of the GNU Affero General Public License
  along with this program. If not, see <http://www.gnu.org/licenses/>.
{% endcomment %}
{% load i18n static %}
{% load kudos_extras %}
<input id="is-authenticated" type="hidden" value={{ user.is_authenticated }}>
{% if user.is_authenticated %}
  <div class="nav-item dropdown interior">
    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
      data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      {{ user }}
    </a>
    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
      {% if source == 'authed' %}
        <a class="dropdown-item" href="{% url "tip" %}">
          <i class="far fa-paper-plane"></i>
          {% trans "Send Tip" %}
        </a>
        <a class="dropdown-item" href="{% url "kudos_marketplace" %}">
          <i class="fas"><img src="{% static "v2/images/kudos/IconKudos.svg" %}"></i>
          {% trans "Send Kudos" %}
        </a>
        <a class="dropdown-item" href="{% url "new_funding" %}">
          <i class="fab fa-ethereum"></i>
          {% trans "Fund Issue" %}
        </a>

        <div class="dropdown-divider"></div>
        <a class="dropdown-item" href="{% url "grants:profile" %}">
          <i class="fas"><img src="{% static "v2/images/grants/icons/black.svg" %}"></i>
          {% trans "My Grants" %}
        </a>
        <a class="dropdown-item" href="{% url "explorer" %}?bounty_filter=createdByMe&network=mainnet&order_by=-web3_created">
          <i class="fas"><img src="{% static "v2/images/grants/icons/black.svg" %}"></i>
          {% trans "My Created Bounties" %}
        </a>
        <a class="dropdown-item" href="{% url "explorer" %}?bounty_filter=startedByMe&network=mainnet&order_by=-web3_created">
          <i class="fas"><img src="{% static "v2/images/grants/icons/black.svg" %}"></i>
          {% trans "My Started Bounties" %}
        </a>
        <div class="dropdown-divider"></div>
      <a class="dropdown-item" href="{% url "onboard" "profile" %}?steps=avatar">
        <i class="fas fa-user-edit"></i>
        {% trans "My Avatar" %}
      </a>
      <a class="dropdown-item" href="{% url "profile" %}">
        <i class="fas fa-user"></i>
        {% trans "My Profile" %}
      </a>
      {% else %}
        <a class="dropdown-item" href="{% url "get_gitcoin" %}">
          <i class="fas fa-bolt"></i>
          {% trans "Get Started" %}
        </a>
      {% endif %}

      <div class="dropdown-divider"></div>
      <a class="dropdown-item" href="{% url "email_settings" email_key %}">
        <i class="fas fa-cog"></i>
        {% trans "Manage Settings" %}
      </a>
      {% if unclaimed_tips %}
        <div class="dropdown-divider"></div>
        {% for tip in unclaimed_tips %}
          <a class="dropdown-item" href="{{ tip.receive_url }}">
            <i class="fas fa-dollar-sign"></i>
            {% trans "Claim" %} ${{ tip.value_in_usdt_now }} {% trans "Tip" %}
          </a>
        {% endfor %}
      {% endif %}
      {% if unclaimed_kudos %}
        <div class="dropdown-divider"></div>
        {% for kudos in unclaimed_kudos %}
          <a class="dropdown-item" href="{{ kudos.receive_url }}">
            <i class="fas fa-gift"></i>
            {% trans "Claim Kudos" %}
          </a>
        {% endfor %}
      {% endif %}
      {% if user.is_staff %}
      <div class="dropdown-divider"></div>
      <a class="dropdown-item" href="{% url "admin:index" %}">
        <i class="fas fa-user-secret"></i>
        {% trans "Administration" %}
      </a>
      {% endif %}
      <div class="dropdown-divider"></div>
      <a class="dropdown-item" href="{% url "logout" %}?next={{ request.get_full_path }}">
        <i class="fas fa-lock"></i>
        {% trans "Log Out" %}
      </a>
    </div>
  </div>
  <a href="/profile/" class="nav_avatar d-none d-md-block"
    style="background-image:url({% if user.profile.active_avatar %}{{ user.profile.active_avatar.avatar_url }}{% else %}/dynamic/avatar/{% if user and user.username %}{{ user.username }}{% else %}Self{% endif %}{% endif %})">
  </a>

{% else %}
  <a class="nav-link login interior" href="{% url 'social:begin' 'github' %}?next={{ request.get_full_path }}"
    onclick="dataLayer.push({'event': 'login'});">
    <i class="fab fa-github"></i><span class="nav-link__text">{% trans "Log in" %}</span>
  </a>
{% endif %}